"""Added product table (revision 2)

Revision ID: 3c66d56daacb
Revises: 4ea4361a6cf6
Create Date: 2023-08-16 12:52:00.078671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c66d56daacb'
down_revision = '4ea4361a6cf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
