"""Added product table

Revision ID: 41499f763398
Revises: c252bc8c03c2
Create Date: 2023-08-16 12:25:32.071192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41499f763398'
down_revision = 'c252bc8c03c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
