"""added saleds

Revision ID: 429cb2015eb4
Revises: 14294ced0a9b
Create Date: 2023-08-18 09:33:50.431457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429cb2015eb4'
down_revision = '14294ced0a9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saled',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=155), nullable=True),
    sa.Column('total_price', sa.String(length=155), nullable=True),
    sa.Column('user', sa.UUID(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saled')
    # ### end Alembic commands ###
