"""User_add_to_db

Revision ID: 573e5843eaee
Revises: d302c2e9ce47
Create Date: 2023-08-07 22:11:18.848484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573e5843eaee'
down_revision = 'd302c2e9ce47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=155), nullable=True),
    sa.Column('username', sa.String(length=155), nullable=False),
    sa.Column('email', sa.String(length=155), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
