"""Added category table

Revision ID: c252bc8c03c2
Revises: 573e5843eaee
Create Date: 2023-08-16 11:45:53.431633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c252bc8c03c2'
down_revision = '573e5843eaee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
